# Generated by Django 2.0.2 on 2018-06-14 12:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Azizi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Mobile_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
