# Generated by Django 2.0.2 on 2018-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Azizi', '0002_auto_20180614_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Intereset',
            field=models.CharField(max_length=1000),
        ),
    ]
